# Generated by Django 4.1.5 on 2023-01-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=20)),
                ('Orders_delivered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('DishID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.FloatField(max_length=100)),
                ('Num_Ordered', models.IntegerField()),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('Table_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50)),
                ('Total_To_Pay', models.FloatField()),
                ('Timer_Status', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50)),
                ('Note', models.CharField(max_length=280)),
                ('DishID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainDatabase.menu')),
                ('Table_Number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainDatabase.tables')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainDatabase.orders')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainDatabase.employees')),
            ],
        ),
    ]
