# Generated by Django 4.1.5 on 2023-01-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDatabase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
